### ISSUE TITLE
version ve cache_version ayarlanmalı

### ISSUE THREAD

**Issue by ertugerata** [safaariman/pisi#15]
https://github.com/ertugerata/BuildFiles/blob/master/system/base/pisi/actions.py#L12 de 2.4 ten 2.6 ya ayarlanması isteniyor ancak __init.py__ de diğer yer 3.0.0-alpha1 ayarlanmış, doğrusu ayarlanmalı.

https://github.com/ertugerata/pisi/blob/master/pisi/db/lazydb.py#L41

**Comment by safaariman** [comment]
Cache versiyonu değiştirildi.
